### PR TITLE
fix: update bullmq dependencies in package.json and bun.lock

### LINKED ISSUE #30: Version 0.5.0 missing bullmq dependency
After updating to version 0.5.0 from 0.4.0 and building locally, the package no longer builds correctly. Bullmq dependencies missing

Image

### PR DESCRIPTION
**Pull request by mycomycul**
- The package file was missing bulmq in version 0.5.0 and prevented the backend from building correctly. I'm not sure if the intention was to remove bullmq with the change to sqllite but this resolves the build issue for now.

- This adds the most recent version of bullmq to th backend package and fixes the build
```
14.68 ERROR in ./src/jobs/services/model-poller.service.ts:3:23
14.68 TS2307: Cannot find module 'bullmq' or its corresponding type declarations.
14.68     1 | import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
14.68     2 | import { InjectQueue } from '@nestjs/bullmq';
14.68   > 3 | import { Queue } from 'bullmq';
14.68       |                       ^^^^^^^^
14.68     4 | import { ConfigService } from '@nestjs/config';
14.68     5 |
14.68     6 | /**
14.68
14.68 webpack 5.97.1 compiled with 6 errors in 12540 ms
```

Fixes #30

### CODE REVIEW

**Comment by wojo-o** [comment]
Appreciate the PR! The direction here is actually the opposite — the SQLite migration removes BullMQ/Redis entirely, so rather than re-adding the dependency, the leftover model-poller files that referenced it are being dropped. That resolves the build without pulling Redis back in.

 Fixed in 0.5.1-beta. I'll plan to close this in favor of removing the dependency — but thanks for digging into it and flagging the breakage! If you open any new pull requests you're very welcome, I appreciate your work. Any questions, drop them here; otherwise I'll go ahead and close this PR.
 
 
 
 ```bash
    docker run -d \
      --name inker \
      --restart unless-stopped \
      -p 80:80 \
      -v inker_postgres:/var/lib/postgresql/17/main \
      -v inker_uploads:/app/uploads \
      wojooo/inker:0.5.1-beta

**Comment by mycomycul** [comment]
@wojo-o That's what I figured, but I needed the change to get going so I figured I'd push it.  Will Close.
